# 服务端口
server:
  port: 80

spring:
  application:
    # 服务名
    name: service-gateway
  cloud:
    # nacos服务地址
    nacos:
      discovery:
        server-addr: 110.40.223.206:8848
        enabled: true
    gateway:
      routes:
        #设置路由id
        - id: service-hospital
          #设置路由的uri
          uri: lb://service-hospital
          #设置路由断言,代理servicerId为auth-service的/auth/路径
          predicates:
            - Path=/*/hosp/**

        - id: service-cmn
          uri: lb://service-cmn
          predicates:
            - Path=/*/cmn/**

        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/*/user/**

        - id: service-msm
          uri: lb://service-msm
          predicates:
            - Path=/*/msm/**

      discovery:
        locator:
          enabled: true
